### ISSUE TITLE
License for contribution

### ISSUE THREAD

**Issue by mtparet** [tytkal/python-hijiri-ummalqura#10]
Hi,

We're actively using your library (by using dateparser) and we'll like to contribute to fixes. 
But your repository is missing a license, could you specify which one you would like ?

Thanks a lot,

Matthieu

**Comment by tytkal** [comment]
Hi, 
I have update README file licence is MIT. 
Thank you :+1:

**Comment by mtparet** [comment]
Thank you @tytkal :)
