### ISSUE TITLE
No module named 'hijri'

### ISSUE THREAD

**Issue by essankov** [tytkal/python-hijiri-ummalqura#6]
I'm using Python 3 after adding

``` python
from umalqurra.hijri_date import HijriDate
```

i got this error:

 lib/python3.5/site-packages/umalqurra/hijri_date.py", line 10, in <module>
    from hijri import Umalqurra
ImportError: No module named 'hijri'

How to fix it?

**Comment by tytkal** [comment]
I haven't update pip repository, for now you can use the code direct from git. 
Note: I haven't test it in python3 I hope It will work let me now if you face any issue

**Comment by essankov** [comment]
It's not working in python3. If you want I can help you with it by hacktoberfest

**Comment by ShakeelRaja** [comment]
same issue here .. could you advise us on how can we possibly use this in 3.5 ??

**Comment by sijms** [comment]
you can do the following to solve the problem
go to python folder (either system or virtualenv folder) then site-packages find folder named umalqurra
in the folder edit the following files

**file:** hijri_date.py
**replace:**  `from hijri import Umalqurra`
**with:** `from umalqurra.hijri import Umalqurra`

**file:** hijri.py
**replace:** `from ummalqura_arrray import UmalqurraArray`
**with:** `from umalqurra.ummalqura_arrray import UmalqurraArray`

**Comment by sijms** [comment]
I am using python 3.4 and python 3.5 on Linux and Mac os machines and the module is working perfectly after the previous correction

**Comment by MosabAwadAhmedAlhadi** [comment]
https://github.com/tytkal/python-hijiri-ummalqura/issues/12#issuecomment-400287021 this guy said the problem is with the repo it self so you can upgrade it, i am in 2020 and the last update is two years ago in the repo so if it's work for you tell me about it

**Comment by MosabAwadAhmedAlhadi** [comment]
Ok i downloaded the packages and place it in the /usr/local/lib/site-package/umalqurra 
and it's worked very fine
